@startuml class diagram
scale 1920*1080

' Classes
class Server {
  - port: number
  - app: express.Express
  - server: express.Server
  + constructor(port: number): Server
  + start(): void
  + close(): void
  - setupRoutes(): void
}
class SiteRoute {
  + setupMiddleware(): Router
}

' Classes - Product
class ProductRoute {
  - productController: ProductController
  - requestValidator: Joi
  + constructor(): ProductRoute
  + setupMiddleware(): Router
}
class ProductController {
  + readProducts(idx: number, limit: number): Product[]
}
class Product {
  + uuid: string
  + name: string
  + description: string
  + price: number
  + unit: string
  + image: string
  + find(query): Product[]
}

' Classes - Cart
class CartRoute {
  - cartController: CartController
  + constructor(): CartRoute
  + setupMiddleware(): Router
}
class CartController {
  + readCart(userId: string): Cart
  + updateProduct(userId: string, productId: string, amount: number): Cart
  + deleteCart(userId: string): void
}
class Cart {
  + userId: string
  + products: CartedProduct[]
  + findOne(conditions, projection, options): Cart
  + findOneAndUpdate(filter, query, options): Cart
  + deleteMany(conditions, options): void
}
class CartedProduct {
  + productId: string
  + amount: number
}

' Classes - User
class UserRoute {
  - userController: userController
  + constructor(): UserRoute
  + setupMiddleware(): Router
}
class UserController {
  + createUser(): string
  + readUser(userId: string): User
  + updateUser(user: User): User
  + authenticateUser(username: string, password: string): string
}
class User {
  + constructor(document)
  + id: string
  + email: string
  + password: string
  + findOne(conditions, projcetion, options): User
  + findOneAndUpdate(filter, query, options): User
  + save(): Promise
}

' Relationships from Server to routes
Server ..> ProductRoute
Server ..> CartRoute
Server ..> SiteRoute
Server ..> UserRoute

' Relationships from routes to controllers
ProductRoute "1\t" *-- "1" ProductController
CartRoute "1 " *-- "1 " CartController
UserRoute "1 " *-- "1  " UserController

' Relationships from controllers to models
ProductController ..> Product
CartController ..> Cart
UserController ..> User

' Relationships between models
Cart ..> CartedProduct
@enduml
