@startuml domain model
scale 1920*1080

' Conceptual classes
class Produkt {
  id
  navn
  beskrivelse
  pris
  enhed
  billede
}
class KurvProdukt {
  bruger id
  produkt id
  antal
}
class Bruger {
  id
  brugernavn
  kodeord
  email
  telefonnummer
}

' Relationships
KurvProdukt "0..m" -r- "1" Produkt: \t\t
Bruger "1" -- "0..m" KurvProdukt

@enduml
