@startuml domain model
scale 1920*1080

' Conceptual classes
class Produkt {
  id
  navn
  beskrivelse
  pris
  enhed
  billede
}
class KurvProdukt {
  bruger id
  produkt id
  antal
}
class Bruger {
  id
  email
  kodeord
}
class Ordre {
  id
  bruger id
  produkter
}
class Betaling {
  id
  status
  ordre
}

' Relationships
KurvProdukt "0..m" -- "1" Produkt: \t\t
Bruger "1" -- "0..m" KurvProdukt
Ordre "0..m" -- "1..m" Produkt
Ordre "1" -- "0..m" Betaling
Bruger "1" -- "0..m" Ordre

@enduml
