@startuml domain model
scale 1920*1080
skinparam defaultFontName "Roboto"
skinparam classAttributeIconSize 0

boundary Express
participant ProductRoute
participant ProductController
participant Product
database MongoDB

Express -> ProductRoute: HTTP request
ProductRoute -> ProductController: readProducts(start, end)
ProductController -> Product: find(query)
Product -> MongoDB
activate MongoDB
Express <- MongoDB: JSON liste af produkter
deactivate MongoDB
@enduml