@startuml sequence diagram
scale 1920*1080
skinparam defaultFontName "Roboto"

boundary Express
participant ProductRoute
participant ProductController
participant Product
database MongoDB

Express -> ProductRoute: GET /api/products
ProductRoute -> ProductController: readProducts(index, limit)
ProductController -> Product: find(query)
Product -> MongoDB
activate MongoDB
Express <- MongoDB: JSON liste af produkter
deactivate MongoDB
@enduml
